Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: true
  EnforcedStyle: space

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets
